Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Shel.Neos.Norman.Nodely:
            - Main

      backendLoginForm:
        logoImage: '' # Thou shall not have a login logo beside Norman!

    Ui:
      resources:
        stylesheets:
          'Shel.Neos.Norman.Nodely:Plugin':
            resource: resource://Shel.Neos.Norman.Nodely/Public/Plugin.css
        javascript:
          'Shel.Neos.Norman.Nodely:Plugin':
            resource: resource://Shel.Neos.Norman.Nodely/Public/Plugin.js

      frontendConfiguration:
        'Shel.Neos.Norman.Nodely:Plugin':
          eyeOffsetDegrees: 60
